API data
artem-silaev/yard-frontend pull request #9
Opened 2017-07-14 20:43 UTC by artem-silaev

https://build-jlswsttlic.now.sh/

2017-07-14 23:40 UTC, evgenyrodionov commented
Плохие коммиты оч

2017-07-14 23:41 UTC, evgenyrodionov commented
Адреса на странице ЖК почему-то нет

2017-07-14 23:41 UTC, evgenyrodionov commented
Тут какие-то левые данные, какая мебель вообще

![image](https://user-images.githubusercontent.com/775692/28234324-160cc2d0-6907-11e7-914a-37da6ea8dd87.png)

2017-07-14 23:41 UTC, evgenyrodionov commented
Кол-во квартир и кол-во предложений совпадает? почему?

2017-07-14 23:41 UTC, evgenyrodionov commented
У кнопок шрифт почему-то проебался

2017-07-14 23:42 UTC, evgenyrodionov commented
логотип не кликабельный

2017-07-15 11:43 UTC, artem-silaev commented
https://build-zyaxeebmiu.now.sh/

2017-07-15 13:24 UTC, imevro requested changes

2017-07-15 13:24 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +    get('complexes?filter%5Bstate%5D=public')
есть encodeURI

2017-07-15 13:24 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +  if (images.length === 0) { return null; }
читай чужие пры

2017-07-15 13:24 UTC, evgenyrodionov commented on src/Complexes/Show/Characteristics.jsx
> +            { constructionKind &&
у тебя преттир сломался или что?

2017-07-15 13:24 UTC, evgenyrodionov commented on src/Complexes/Show/MainTitle.jsx
> +          <Name>{`Жилой комплекс «${props.name}»`}</Name>
зачем тут интерполяция строки

2017-07-15 13:24 UTC, evgenyrodionov commented on src/utils.js
> +export function getPhotoCountLocale(count) {
гугли плюралайзер

2017-07-15 13:24 UTC, evgenyrodionov commented on src/utils.js
> +export const get = resource => fetch(API_URL + resource).then(res => res.json());
это вообще не про утилс, вынеси работу с апи в отдельный файл

2017-07-15 13:25 UTC, imevro requested changes

2017-07-15 13:25 UTC, evgenyrodionov commented on src/utils.js
> +const API_URL = 'https://yard.moscow/api/v1/';
Зачем кстати ТАК_ОРАТЬ?

2017-07-15 16:57 UTC, artem-silaev commented
https://build-qasqjbkdwh.now.sh/

2017-07-15 17:45 UTC, evgenyrodionov commented
Слишком большая дыра

![image](https://user-images.githubusercontent.com/775692/28241506-82c1c988-699e-11e7-9f68-c335d717b683.png)

2017-07-15 17:54 UTC, imevro requested changes

2017-07-15 17:54 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +          complexes: json.items,
http://2ality.com/2015/01/es6-destructuring.html
Если использовать es6 destructing + альясы неймов + object shorthand, то можно сделать так:

```jsx
// destructing
.then(({ items }) => {
  this.setState({ complexes: items })
})

// с альясом
.then(({ items: complexes }) => {
  this.setState({ complexes: complexes })
})

// object shorthand
.then(({ items: complexes }) => {
  this.setState({ complexes })
})
```

2017-07-15 17:54 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +  const images = props.images || [];
опять же доставай дестрактом + деф параметры

`export default ({ images = [], ...props }) => {}`

2017-07-15 17:54 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +  const images = props.images || [];
три точки это rest оператор — в props будут все остальные ключи объекта props за исключением images, потому что мы его вытащили

2017-07-15 17:54 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +  if (images.length !== 0) {
вынеси проверку уровень выше и вообще не рендерь этот компонент

2017-07-15 17:54 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +  if (images.length !== 0) {
https://facebook.github.io/react/docs/conditional-rendering.html#inline-if-with-logical--operator

2017-07-15 17:54 UTC, evgenyrodionov commented on src/Complexes/Show/Characteristics.jsx
> +              {kinds[propertyKind || 'flat']}
https://github.com/3s777/yard-frontend/pull/7#pullrequestreview-50193926

2017-07-15 17:54 UTC, evgenyrodionov commented on src/Complexes/Show/Infrastructure.jsx
> +      {amenities.length > 0 && <Title>Инфраструктура</Title>}
опять же вынеси вверх

2017-07-15 17:54 UTC, evgenyrodionov commented on src/Complexes/Show/Infrastructure.jsx
> +  const { amenities = [] } = props;
можно сразу в аргументе функции это делать

2017-07-15 17:54 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +    if (!complex.id) { return null; }
нет

2017-07-15 17:54 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +    if (!complex.id) { return null; }
некрасивый флэш контента будет

2017-07-15 17:54 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +        <Helmet>
красава

2017-07-15 17:54 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +              {complex.fullDescription && <Description text={complex.fullDescription} />}
text={fullDescription}? держи данные согласованными

2017-07-15 17:54 UTC, evgenyrodionov commented on src/Complexes/api.js
> +/* eslint import/prefer-default-export: 0 */
опять же поставь TODO

2017-07-15 20:19 UTC, artem-silaev commented
https://build-ehghshjtfb.now.sh/

2017-07-15 21:08 UTC, evgenyrodionov commented
Где согласованность

![image](https://user-images.githubusercontent.com/775692/28242686-e7a6a474-69ba-11e7-93df-ab94d04acfaf.png)

2017-07-15 21:08 UTC, evgenyrodionov commented
Пункты перепутаны местами, в макете не так

![image](https://user-images.githubusercontent.com/775692/28242687-f4ac7c02-69ba-11e7-9ebd-b0d5bdbb9f7c.png)

2017-07-15 21:10 UTC, imevro requested changes

2017-07-15 21:10 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
>      get(encodeURI('complexes?filter[state]=public'))
вынеси энкодюри в гет функцию-то

2017-07-15 21:10 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +    get(`complexes/${this.props.match.params.slug}`).then(data => this.setState({ complex: data }));
а тут чё не дожал с object shorthand

2017-07-15 21:10 UTC, evgenyrodionov commented on src/Complexes/api.js
> +// TODO: remove sometime this rule
напиши когда конкретно, а не самтайм

2017-07-15 22:13 UTC, artem-silaev commented
https://build-sisikrzrda.now.sh

2017-07-17 10:09 UTC, imevro approved these changes

2017-07-17 10:09 UTC, merged

2017-07-17 10:10 UTC, evgenyrodionov commented
новый бранч от мастера делай, не забудь гит пулл --ребейз